# Generated by Django 5.0.7 on 2024-07-17 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
