# Generated by Django 5.0.7 on 2024-07-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0005_order_waiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('cooking', 'Cooking'), ('delivered', 'Delivered')], default='ordered', max_length=20),
        ),
    ]
